CUDA_VISIBLE_DEVICES=1 python train.py \
-s "/scratch-ssd/Datasets/deformgs/synthetic/scene_3_whole/" \
--port 6058 \
--expname "synthetic/scene_3_whole_skip_5_masks" \
--configs "arguments/mdnerf-dataset/cube.py" \
--lambda_w 2000 \
--lambda_rigidity 0.0 \
--lambda_spring 0.0 \
--lambda_momentum 0.03 \
--lambda_velocity 0.0 \
--view_skip 5 \
--time_skip 1 \
--k_nearest 20 \
--lambda_isometric 0.3 \
--reg_iter 11000 \
--staticfying_from 10000 \
--use_wandb \
--wandb_project "synthetic_scene_3" \
--wandb_name "synthetic_full_skip5_masks"
